"use strict";

const LATIN_MAP = [
  [/\bhr\b/gi,                                    "хүний нөөц"],
  [/\bit\b/gi,                                    "мэдээллийн технологи"],
  [/gereltuuleg|gereltüüleg|gereltuuleh/gi,   "гэрэлтүүлэг"],
  [/ger\s*horoolol|ger\s*horooliin|ger\s*horoolliin|ger\s*horoollyn/gi, "гэр хороолол"],
  [/tsamhagt|tsamhagiin|tsamhag/gi,           "цамхаг"],
  [/asalt/gi,                                  "асалт"],
  [/assan/gi,                                  "ассан"],
  [/yalltiin|yalaltiin|yalalt/gi,              "ялалт"],
  [/egneenii|egnee/gi,                         "эгнээ"],
  [/gudamnii|gudamjnii/gi,                     "гудамж"],
  [/autozam|auto\s*zam|avto\s*zam/gi,          "авто зам"],
  [/hunii\s*noots|hunii\s*nots|hünii\s*nöts/gi, "хүний нөөц"],
  [/gerlen\s*dohio|gerelt\s*dohio|gerel\s*dohio/gi, "гэрлэн дохио"],
  [/gerliin\s*shon/gi,                          "гэрлийн шон"],
  [/sankhuu/gi,                                 "санхүү"],
  [/gerel/gi,                                   "гэрэл"],
  [/gudamj/gi,                                  "гудамж"],
  [/choibalsan/gi,                              "чойбалсан"],
  [/chita/gi,                                   "чита"],
  [/uurhai/gi,                                  "уурхай"],
  [/gemtel/gi,                                  "гэмтэл"],
  [/zasvar/gi,                                  "засвар"],
  [/irtsiin|irtsiig/gi,                         "ирцийн"],
  [/\birts\b/gi,                                "ирц"],
  [/nyagtlan|njagtlan/gi,                       "нягтлан"],
  [/naygtlan|nyagtlan|njagtlan/gi,              "нягтлан"],
  [/narav|naraviin|nyarav|njarav/gi,            "нярав"],
  [/zahiral|zakhiral/gi,                        "захирал"],
  [/tailan|taylan/gi,                           "тайлан"],
  [/huvaari|khuvaar/gi,                         "хуваарь"],
  [/aguulah|agwlah/gi,                          "агуулах"],
  [/\bdohio\b/gi,                               "дохио"],
  [/habea/gi,                                   "хабэа"],
  [/ajiltan/gi,                                 "ажилтан"],
  [/\bajil\b|ajild|ajliin/gi,                   "ажил"],
  [/tsalin/gi,                                  "цалин"],
  [/batalgaa/gi,                                "баталгаа"],
  [/noots|nöts/gi,                              "нөөц"],
  [/unuudur/gi,                                 "өнөөдөр"],
  [/heden/gi,                                   "хэдэн"],
  [/heded/gi,                                   "хэдэд"],
  [/asahaar|asah|asaah/gi,                      "аса"],
  [/untarhaar|untarah/gi,                       "унтрах"],
  [/herhen/gi,                                  "хэрхэн"],
  [/\bniit\b/gi,                                "нийт"],
  [/\bbugd\b|\bbugdiin\b|\bbuh\b|\bbusad\b/gi, "бүх"],
  [/irsen/gi,                                   "ирсэн"],
  [/\bshon\b/gi,                                "шон"],
  [/\btoo\b/gi,                                 "тоо"],
  [/surgalt/gi,                                 "сургалт"],
  [/gereet/gi,                                  "гэрээт"],
  [/gereet\b/gi,                                "гэрэ"],
  [/\bgeree\b/gi,                               "гэрээ"],
  [/tsahilgaan/gi,                              "цахилгаан"],
  [/enegener|engener|injener/gi,                "инженер"],
  [/medeel/gi,                                  "мэдээлэл"],
  [/gemtl/gi,                                   "гэмтэл"],
  [/\btolgoi\b/gi,                              "толгой"],
  [/\bhed\b/gi,                                 "хэдэн"],
  [/\bner\b/gi,                                 "нэр"],
  [/\bashgvi\b|\bashgui\b|\basahgvi\b|\basahgui\b/gi, "асахгүй"],
  [/\bgargaj\b|\bgargaach\b/gi,                 "гаргаж"],
  [/\bharuul|\bharuulj\b/gi,                    "харуулаач"],
  [/\baviach\b|\bavch\b|\bug\b|\buguuch\b/gi,   "өгөөч"],
  [/\bbna\b/gi,                                 "байна"],
  [/\bbaidag\b/gi,                              "байдаг"],
  [/\bnadin\b|\bnadad\b/gi,                     "надад"],
  [/\bnadaad\b/gi,                              "надад"],
  [/\bhen\b/gi,                                 "хэн"],
  [/\bgedeg\b/gi,                               "гэдэг"],
  [/\byamar\b/gi,                               "ямар"],
  [/hiideg|hiisen|hiij/gi,                      "хийдэг"],
  [/\bbaidag\s*ve\b/gi,                         "байдаг вэ"],
  [/ajilchid/gi,                                "ажилчид"],
  [/\bners/gi,                                  "нэрс"],
  [/cameriin|cameriinх|kameriin|camera-iin/gi,  "камерын"],
  [/camer|camera|kamer/gi,                      "камер"],
  [/hvnii\s*nuuts|hunii\s*nuuts|hunii\s*noots/gi, "хүний нөөц"],
  [/tulbur/gi,                                  "төлбөр"],
  [/utas/gi,                                    "утас"],
  [/dugar|dugaar|dugaarig|dugaariig/gi,         "дугаар"],
  [/tselmeg/gi,                                 "цэлмэг"],
  [/nemeh\s*bayar|nemekh\s*bayar|nemehbayar|nemekhbayar|nemeh\s*bayr/gi, "нэмэхбаяр"],
  [/undraa/gi,                                  "ундраа"],
  [/tvvnii|tuunii/gi,                           "түүний"],
  [/minii/gi,                                   "миний"],
  [/svvl/gi,                                    "сүүл"],
  [/sariin|sar/gi,                              "сарын"],
  [/tulburiin|tulbur/gi,                        "төлбөр"],
  [/bolovsoroltoi|bolovsroltoi|bolovsorol|bolovsrol/gi, "боловсрол"],
  [/\borson\b|\borood\b/gi,                     "орсон"],
  [/\bond\b|\bon\b/gi,                          "онд"],
  [/baiguulgad|baiguullagad|baiguullaga/gi,     "байгууллагад"],
  [/enkhbolor|ekhbolor/gi,                      "энхболор"],
  [/\bahmad\b/gi,                               "ахмад"],
  [/\bniis\b|\bniit\b/gi,                       "нийт"],
  [/emegt/gi,                                   "эмэгт"],
  [/eregt/gi,                                   "эрэгт"],
  [/\bgazar\b/gi,                               "газар"],
  [/tasaldaг|tasalddag/gi,                      "тасалддаг"],
];

function cyrillize(text) {
  let t = text;
  for (const [pat, rep] of LATIN_MAP) t = t.replace(pat, rep);
  return t;
}

module.exports = { cyrillize, LATIN_MAP };
